{"level":"error","message":"DB Sync error: password authentication failed for user \"buddydesk_user\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":110,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":110,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"buddydesk_user\"\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (E:\\Node\\buddyDesk\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-08-04T18:14:23.740Z"}
{"level":"error","message":"DB Sync error: password authentication failed for user \"buddydesk_user\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":110,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":110,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"buddydesk_user\"\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (E:\\Node\\buddyDesk\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:524:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-08-04T18:15:00.605Z"}
{"level":"error","message":"DB Sync error: read ECONNRESET","name":"SequelizeConnectionError","original":{"code":"ECONNRESET","errno":-4077,"syscall":"read"},"parent":{"code":"ECONNRESET","errno":-4077,"syscall":"read"},"stack":"SequelizeConnectionError: read ECONNRESET\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:524:28)\n    at Socket.reportStreamError (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-08-04T18:18:11.199Z"}
{"level":"error","message":"DB Sync error: read ECONNRESET","name":"SequelizeConnectionError","original":{"code":"ECONNRESET","errno":-4077,"syscall":"read"},"parent":{"code":"ECONNRESET","errno":-4077,"syscall":"read"},"stack":"SequelizeConnectionError: read ECONNRESET\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:524:28)\n    at Socket.reportStreamError (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-08-04T18:19:57.434Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:12:18.287Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:12:59.218Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:13:06.710Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:14:34.955Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:15:10.079Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:21:17.375Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:21:31.185Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:21:52.753Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:22:10.890Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:22:25.326Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:22:39.036Z"}
{"level":"error","message":"DB Sync error: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at Client._connectionCallback (E:\\Node\\buddyDesk\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:149:20)\n    at Connection.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\client.js:149:18)\n    at Object.onceWrapper (node:events:638:28)\n    at Connection.emit (node:events:524:28)\n    at Socket.<anonymous> (E:\\Node\\buddyDesk\\node_modules\\pg\\lib\\connection.js:62:12)\n    at Socket.emit (node:events:536:35)\n    at TCP.<anonymous> (node:net:343:12)","timestamp":"2025-08-04T19:22:51.919Z"}
